### ISSUE TITLE
Import tensorflow in Python Error:   libcusolver.so.8.0 not found

### ISSUE THREAD

**Issue by lifematrix** [jetsonhacks/installTensorFlowJetsonTX#5]
Hey, thank you for your nice work.
I install tensorflow python package downloaded from your repository on my TX-2.
However, it report error when import tensorflow:

```
ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory
Failed to load the native TensorFlow runtime.
```

I know the reason is a conflict about version of CUDA.  I installed [jetpack](http://docs.nvidia.com/jetpack-l4t/2_1/content/developertools/mobile/jetpack/jetpack_l4t/2.0/jetpack_l4t_install.htm) , it contain cuda 9.0, but tensorflow package is built with cuda 8.0. 

How can I solve it? Do I have to compile tensorflow from scratch?

Thank you!

**Comment by jetsonhacks** [comment]
I believe that you have to recompile it to link with CUDA 9.

**Comment by lifematrix** [comment]
OK, I know. Thanks!

**Comment by trohit920** [comment]
Hello @lifematrix  @jetsonhacks I am also facing the same problem. Can you tell me how you solved this issue? Did you mean to built it from source and redefine the correct CUDA version in installTensorlfow.sh?

**Comment by jetsonhacks** [comment]
The .whl are for CUDA 8.0. This is an older version. You should install from: https://devtalk.nvidia.com/default/topic/1031300/jetson-tx2/tensorflow-1-9-rc-wheel-with-jetpack-3-2-/1

**Comment by trohit920** [comment]
Thanks for your reply. However i have TX1 so does these wheel file works on TX1?

**Comment by jetsonhacks** [comment]
Yes

**Comment by trohit920** [comment]
Thank you very much for your help.
