### ISSUE TITLE
Wheel files for L4T 27.1

### ISSUE THREAD

**Issue by aviziskind** [jetsonhacks/installTensorFlowJetsonTX#7]
I am trying to install tensorflow on my Jetson TX2, which, for compatibility reasons with other programs, I need to keep with L4T 27.1 (CUDA 8, CUDNN 5.1). Can you please add to this repository the python wheel files for L4T version 27.1?
Thanks!

**Comment by jetsonhacks** [comment]
My path is not towards the past. You can refer to the article on how to build TensorFlow for 27.1 for yourself:
http://www.jetsonhacks.com/2017/04/02/tensorflow-on-nvidia-jetson-tx2-development-kit/
or search for a pre-built wheel file (Maybe here):
https://devtalk.nvidia.com/default/topic/1000717/jetson-tx2/tensorflow-on-jetson-tx2/1

**Comment by aviziskind** [comment]
Thanks for the tip! That first post in that devtalk.nvidia.com provided a [link](https://drive.google.com/file/d/0Bxl-G9VJ61mBYmZPY0hLSlFaUDg/view?usp=sharing) to a wheel file (tensorflow-1.0.1-cp27-cp27mu-linux_aarch64.whl) that was compatible with my L4T 27.1 setup.
